import { ArrowRight, BadgeDollarSign, Ban, Bell, Bold, BookPlus, BookUser, CalendarDays, ChartBarStacked, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronsLeftRightEllipsis, ChevronsUpDown, CircleFadingPlus, CircleUserRound, Code, createIcons, CreditCard, Database, Eye, Facebook, Factory, FileText, Film, Globe, Heading2, Heading3, Heading4, Heart, House, Image, Info, Instagram, Italic, Link, List, ListOrdered, Logs, Mail, MailCheck, MapPin, Menu, MoveLeft, MoveRight, Phone, PhoneOutgoing, Pilcrow, Plus, Power, Quote, Rss, ScrollText, Search, Send, Settings, ShieldAlert, ShoppingCart, SquarePen, Target, TicketPercent, Trash2, Twitter, Underline, User, UserCircle, UserPen, Users, X, Youtube } from 'lucide';



document.addEventListener('DOMContentLoaded', () => {
    createIcons({
        attrs: {
            'stroke-width': 1.5,
        },
        icons: {
            House,
            ShoppingCart,
            ChartBarStacked,
            Target,
            Logs,
            TicketPercent,
            Film,
            BadgeDollarSign,
            ScrollText,
            MailCheck,
            Users,
            Rss,
            BookPlus,
            Settings,
            CircleFadingPlus,
            Info,
            ChevronsLeftRightEllipsis,
            CreditCard,
            Plus,
            ChevronLeft,
            ChevronRight,
            MoveLeft,
            Pilcrow,
            Heading2,
            Heading3,
            Heading4,
            Bold,
            Italic,
            Underline,
            Code,
            List,
            ListOrdered,
            Menu,
            Database,
            Globe,
            Bell,
            ChevronDown,
            X,
            Check,
            Eye,
            FileText,
            CircleUserRound,
            CalendarDays,
            ChevronsUpDown,
            Search,
            Trash2,
            SquarePen,
            Heart,
            UserCircle,
            MoveRight,
            MapPin,
            UserPen,
            Image,
            Power,
            Ban,
            Facebook,
            Instagram,
            Twitter,
            Youtube,
            PhoneOutgoing,
            Mail,
            Factory,
            BookUser,
            ShieldAlert,
            User,
            Quote,
            ArrowRight,
            Phone,
            Link,
            Send
        }
    });
});